version: "3.9"

# cleanup:

# docker container prune -f && docker volume prune -f
# docker system prune -a

services:
  nettside: # https://hub.docker.com/_/php
    #image: php:7.4-cli
    build: .
    volumes:
      - .:/usr/src/nettside
    working_dir: /usr/src/nettside
    command: ./dev.sh
    environment:
      - DOCKER_HOST=0.0.0.0
      - DOCKER_PORT=1080
    ports:
      - 1080:1080
    user: "${DOCKER_USER}"
